version: '3.6'

services:
  redis:
    image: redis:4-alpine
    volumes:
      - app-redis:/var/lib/redis/data
  sidekiq:
    build: .
    environment:
      REDIS_URL: redis://redis:6379/0
    command: bundle exec sidekiq
    volumes:
      - ./:/app
    ports:
      - 8081:8081
    links:
      - redis
    depends_on:
      - redis
      - db
  web:
    build: .
    volumes:
      - ./:/app
    working_dir: /app
    command: puma
    ports:
      - 3000:3000
    depends_on:
      - db
      - sidekiq
      - redis
    environment:
      DATABASE_URL: postgres://postgres@db
      REDIS_URL: redis://redis:6379/0
  db:
    image: postgres:10.3-alpine

volumes:
  app-db:
  app-redis: