version: '3.6'

services:
  redis:
    image: redis:4-alpine
    volumes:
      - app-redis:/var/lib/redis/data
  sidekiq:
    build: .
    env_file:
      - .env
    command: bundle exec sidekiq
    volumes:
      - ./:/app
    ports:
      - 8081:8081
    links:
      - redis
    depends_on:
      - redis
      - db
  web:
    build: .
    volumes:
      - ./:/app
    working_dir: /app
    command: puma
    ports:
      - 80:80
    depends_on:
      - db
      - sidekiq
      - redis
    stdin_open: true
    tty: true
    env_file:
      - .env
  db:
    image: postgres:10.3-alpine
    env_file:
      - .env

volumes:
  app-db:
  app-redis: